---
name: "Bug Report"
description: "File an issue about a software bug."
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: bug_description
    attributes:
      label: Describe the bug
      placeholder: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: bug_expected
    attributes:
      label: Expected behaviour
      placeholder: A concise description of what you expected to happen.
    validations:
      required: false

  - type: textarea
    id: bug_reproduce
    attributes:
      label: Steps to reproduce
      placeholder: >-
        Please provide steps to help us reproducing the behaviour and
        therefore increasing the chance of a swift fix. Preferably give
        a minimal failing example without external dependencies. For
        datasets provide a download link.
    validations:
      required: false

  - type: textarea
    id: bug_more_info
    attributes:
      label: Additional information
      placeholder: >-
        Please also add additional information that can help us, such as:
        the version, the Python version and the operating system you
        are using.
    validations:
      required: false
