name: Linux CI

on:
  pull_request:
  push:
    branches:
      - "main"

env:
    source-directory: $GITHUB_WORKSPACE
    build-directory: /tmp/build

jobs:

    build:
        runs-on: ubuntu-24.04
        timeout-minutes: 30

        steps:

            - name: Checkout project
              uses: actions/checkout@v4

            - name: Configure system
              run: |
                  sudo apt install ninja-build cmake \
                  liblua5.4-dev libboost-all-dev libtbb-dev nanobind-dev libbz2-dev \
                  python3-sphinx python3-pandas python3-sphinx-autodoc-typehints \
                  python3-myst-parser


            - name: Configure project
              shell: bash -l {0}
              run: |
                  mkdir ${{ env.build-directory }}
                  cmake \
                    -G "Ninja" \
                    -D CMAKE_C_COMPILER=clang-18 \
                    -D CMAKE_CXX_COMPILER=clang++-18 \
                    -S ${{ env.source-directory }} \
                    -B ${{ env.build-directory }}

            - name: Build project
              shell: bash -l {0}
              run: |
                  cmake --build ${{ env.build-directory }} --target documentation

            - name: Test project
              shell: bash -l {0}
              run: |
                  ctest --test-dir ${{ env.build-directory }} --output-on-failure


            # see: https://github.com/actions/upload-pages-artifact
            - name: Archive artifact
              shell: bash -l {0}
              run: |
                tar \
                  --dereference --hard-dereference \
                  --directory "documentation/_build/" \
                  -cvf "$RUNNER_TEMP/artifact.tar" \
                  .
